services:
  # Next.js application
  mfe-web-app:
    container_name: mfe-web-app
    build:
      context: ../.. # Go up 2 levels to project root
      dockerfile: docker/apps/mfe-web-app/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mfe-network
    environment:
      - NODE_ENV=production

  # Nginx reverse proxy
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/demo-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mfe-web-app
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge
