services:
  # Next.js application
  web-app:
    container_name: web-app
    build:
      context: ../.. # Go up 2 levels to project root
      dockerfile: docker/apps/mfe-web-app/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mfe-network
    environment:
      - NODE_ENV=production

  # Nginx reverse proxy
  nginx:
    container_name: nginx-proxy
    build:
      context: ../..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/demo-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-app
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge
